# Get me
GET http://localhost:8899/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzk2OTA4LCJleHAiOjE3NjMwOTI5MDh9.7cz4XaZ5QvHy-xEioKNY5oGnNyeh5rCkjpJ6aaxfbZk

###
GET http://localhost:8899/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzk2OTA4LCJleHAiOjE3NjMwOTI5MDh9.7cz4XaZ5QvHy-xEioKNY5oGnNyeh5rCkjpJ6aaxfbZk

###

# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
 "identity" : "1111111116",
#  "identity" : "someone@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###

# Login api
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "andy@ggg.mail",
 "password" : "123456"
}
###




