# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
"identity" : "1111111114",
#  "identity" : "someone@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###





