# getMe api

GET http://localhost:8899/api/auth/me 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzYxNzU0MjI5LCJleHAiOjE3NjMwNTAyMjl9.dG9TNiU8jUDiJvx6yn1_kAjzcYBKOLxmilrzXguJReY


# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
"identity" : "1111111114",
#  "identity" : "someone@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###

# Login api
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "bobby@ggg.mail",
 "password" : "123456"
}
###




